//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.04.01 at 12:30:47 PM CDT 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "uri:oozie:email-action:0.1", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package com.practicalHadoop.oozieEmail;
