Converter:
	javac -d . java/util/Observer.java java/util/Observable.java
	javac -d . -bootclasspath ".:/usr/lib/jvm/java-1.5.0/jre/lib/rt.jar" com/converter/Converter.java
# replace : by ; for Windows
run:
	java com.converter.Converter
