//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.18 at 10:18:15 AM CDT 
//


package com.practicalHadoop.hbase.tables.configuration;

import java.math.BigInteger;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for columnFamily complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="columnFamily">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="name" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="purpose" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *         &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="max_versions" type="{http://www.w3.org/2001/XMLSchema}integer" minOccurs="0"/>
 *         &lt;element name="ompression_type" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *         &lt;element name="in_memory" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="block_cache_enabled" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *         &lt;element name="time_to_live" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="maxBlockSize" type="{http://www.w3.org/2001/XMLSchema}int" minOccurs="0"/>
 *         &lt;element name="bloom_filter" type="{http://www.w3.org/2001/XMLSchema}boolean" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "columnFamily", propOrder = {
    "name",
    "purpose",
    "description",
    "maxVersions",
    "ompressionType",
    "inMemory",
    "blockCacheEnabled",
    "timeToLive",
    "maxBlockSize",
    "bloomFilter"
})
public class ColumnFamily {

    @XmlElement(required = true)
    protected String name;
    @XmlElement(required = true)
    protected String purpose;
    protected String description;
    @XmlElement(name = "max_versions")
    protected BigInteger maxVersions;
    @XmlElement(name = "ompression_type")
    protected String ompressionType;
    @XmlElement(name = "in_memory")
    protected Boolean inMemory;
    @XmlElement(name = "block_cache_enabled")
    protected Boolean blockCacheEnabled;
    @XmlElement(name = "time_to_live")
    protected Integer timeToLive;
    protected Integer maxBlockSize;
    @XmlElement(name = "bloom_filter")
    protected Boolean bloomFilter;

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the purpose property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPurpose() {
        return purpose;
    }

    /**
     * Sets the value of the purpose property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPurpose(String value) {
        this.purpose = value;
    }

    /**
     * Gets the value of the description property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDescription() {
        return description;
    }

    /**
     * Sets the value of the description property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDescription(String value) {
        this.description = value;
    }

    /**
     * Gets the value of the maxVersions property.
     * 
     * @return
     *     possible object is
     *     {@link BigInteger }
     *     
     */
    public BigInteger getMaxVersions() {
        return maxVersions;
    }

    /**
     * Sets the value of the maxVersions property.
     * 
     * @param value
     *     allowed object is
     *     {@link BigInteger }
     *     
     */
    public void setMaxVersions(BigInteger value) {
        this.maxVersions = value;
    }

    /**
     * Gets the value of the ompressionType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOmpressionType() {
        return ompressionType;
    }

    /**
     * Sets the value of the ompressionType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOmpressionType(String value) {
        this.ompressionType = value;
    }

    /**
     * Gets the value of the inMemory property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isInMemory() {
        return inMemory;
    }

    /**
     * Sets the value of the inMemory property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setInMemory(Boolean value) {
        this.inMemory = value;
    }

    /**
     * Gets the value of the blockCacheEnabled property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBlockCacheEnabled() {
        return blockCacheEnabled;
    }

    /**
     * Sets the value of the blockCacheEnabled property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBlockCacheEnabled(Boolean value) {
        this.blockCacheEnabled = value;
    }

    /**
     * Gets the value of the timeToLive property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getTimeToLive() {
        return timeToLive;
    }

    /**
     * Sets the value of the timeToLive property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setTimeToLive(Integer value) {
        this.timeToLive = value;
    }

    /**
     * Gets the value of the maxBlockSize property.
     * 
     * @return
     *     possible object is
     *     {@link Integer }
     *     
     */
    public Integer getMaxBlockSize() {
        return maxBlockSize;
    }

    /**
     * Sets the value of the maxBlockSize property.
     * 
     * @param value
     *     allowed object is
     *     {@link Integer }
     *     
     */
    public void setMaxBlockSize(Integer value) {
        this.maxBlockSize = value;
    }

    /**
     * Gets the value of the bloomFilter property.
     * 
     * @return
     *     possible object is
     *     {@link Boolean }
     *     
     */
    public Boolean isBloomFilter() {
        return bloomFilter;
    }

    /**
     * Sets the value of the bloomFilter property.
     * 
     * @param value
     *     allowed object is
     *     {@link Boolean }
     *     
     */
    public void setBloomFilter(Boolean value) {
        this.bloomFilter = value;
    }

}
