package com.packt.dependencyManagement.chapter6;

import lombok.Data;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

// We would have added the annotation @ManageBean, but we will not, because beans resolution is performed by Spring
/*
* this class is declared as a Spring Component
*/
@Component
@Scope("singleton")
@Data
public class AnyBean {
    @Autowired
    private AnyService anyService;
   
    //Getter and setter are generated by Lombok
    private String color;

    public String process() {
        anyService.callService();
        return "index";
    }
}