package com.packt.dependencyManagement.chapter6;

import lombok.Data;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

/*
* this class is declared as a Spring service
*/
@Service
@Data
/**
 * Service that call the DAO
 */
public class AnyService {
    @Autowired
    //Getter and setter are generated by Lombok
    private AnyDao anyDao;

    public void callService() {
        anyDao.callDao();
    }

}
