//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.06.18 at 10:18:15 AM CDT 
//


package com.practicalHadoop.lucene.tables.configuration;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.navteq.lucene.hbase.tables.configuration package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Tables_QNAME = new QName("http://lucene.practicalHadoop.com/tables/configuration", "tables");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.navteq.lucene.hbase.tables.configuration
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link TableType }
     * 
     */
    public TableType createTableType() {
        return new TableType();
    }

    /**
     * Create an instance of {@link TablesType }
     * 
     */
    public TablesType createTablesType() {
        return new TablesType();
    }

    /**
     * Create an instance of {@link ColumnFamily }
     * 
     */
    public ColumnFamily createColumnFamily() {
        return new ColumnFamily();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TablesType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://lucene.practicalHadoop.com/tables/configuration", name = "tables")
    public JAXBElement<TablesType> createTables(TablesType value) {
        return new JAXBElement<TablesType>(_Tables_QNAME, TablesType.class, null, value);
    }

}
