/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package com.practicalHadoop.lucene.document;

@SuppressWarnings("all")
public class TermsOffset extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
  public static final org.apache.avro.Schema SCHEMA$ = org.apache.avro.Schema.parse("{\"type\":\"record\",\"name\":\"TermsOffset\",\"namespace\":\"com.practicalHadoop.lucene.document\",\"fields\":[{\"name\":\"startOffset\",\"type\":\"int\"},{\"name\":\"endOffset\",\"type\":\"int\"}]}");
  public int startOffset;
  public int endOffset;
  public org.apache.avro.Schema getSchema() { return SCHEMA$; }
  // Used by DatumWriter.  Applications should not call. 
  public java.lang.Object get(int field$) {
    switch (field$) {
    case 0: return startOffset;
    case 1: return endOffset;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
  // Used by DatumReader.  Applications should not call. 
  @SuppressWarnings(value="unchecked")
  public void put(int field$, java.lang.Object value$) {
    switch (field$) {
    case 0: startOffset = (java.lang.Integer)value$; break;
    case 1: endOffset = (java.lang.Integer)value$; break;
    default: throw new org.apache.avro.AvroRuntimeException("Bad index");
    }
  }
}
